### PR TITLE
Added polish translations.

### PR DESCRIPTION
**Pull request by r0d0dendr0n**

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey there, thanks for helping out translating Mycroft Skills. 

Can I clarify, are these changes already added to translate.mycroft.ai and just haven't been pulled across yet?

In case you haven't seen it yet, that link is where we manage all translations for Skills and core.

**Comment by r0d0dendr0n** [comment]
I'm sorry, I had no idea about translate.mycroft.ai. They are just published here.

**Comment by krisgesling** [comment]
We should be able to merge them here, but it would be good to add the translations to the Translate platform as it will overwrite the changes here on future syncs.

**Comment by krisgesling** [comment]
Oh to merge any PR's here we'll also need a signed CLA. This isn't required on translate.mycroft.ai

To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any code contribution. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

You will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors)!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

Thank you!

**Comment by r0d0dendr0n** [comment]
CLA's signed.

**Comment by krisgesling** [comment]
Looks like this has grabbed the translations from translate.mycroft.ai already. 

Any changes directly to the repo will continue to be overwritten so I'm going to close this PR.

**Pull request closed without merging**
